### PR TITLE
Include option to use PointCloud Transport

### PR DESCRIPTION
**Pull request by elsayedelsheikh**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | #4042 |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | Gazebo |
| Does this PR contain AI generated software? | No |

---

## Description of contribution in a few bullet points
Include option to use [point_cloud_transport](https://github.com/ros-perception/point_cloud_transport) so that it works out of the box for the users.
- [x] obstacle_layer/voxel_layer plugins
- [x] collision_monitor node

## Description of documentation updates required from your changes
New parameter `point_cloud_transport` to tune with default value set to `"raw"` that works with regular `PointCloud2` without any compression.
```bash
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: pointcloud
        pointcloud:
          topic: /rgbd_camera/points
          data_type: "PointCloud2"
          transport_type: "raw" # Options: https://github.com/ros-perception/point_cloud_transport?tab=readme-ov-file#known-transports

```

## Description of how this change was tested
I used turtelbot4 gazebo simulation and used [depth_image_processing](https://github.com/ros-perception/image_pipeline/tree/746268fcfd21b389bc39ae60bb6345a53c838558/depth_image_proc) to publish `PointCloud2` out of (rgb and depth) images, my launch file:
<details>
<summary>Click to show</summary>

```Python
from launch import LaunchDescription
from launch_ros.actions import ComposableNodeContainer
from launch_ros.descriptions import ComposableNode

def generate_launch_description():

    container = ComposableNodeContainer(
        name='depth_image_proc_container',
        namespace='',
        package='rclcpp_components',
        executable='component_container',
        composable_node_descriptions=[
            ComposableNode(
                package='depth_image_proc',
                plugin='depth_image_proc::PointCloudXyzrgbNode',
                name='point_cloud_xyzrgb_node',
                remappings=[
                    ('rgb/image_rect_color', 'rgbd_camera/image'),
                    ('depth_registered/image_rect', 'rgbd_camera/depth_image'),
                    ('points', 'rgbd_camera/points'),
                ],
            ),
        ]
    )

    return LaunchDescription([container])
```

</details>

---

## Future work that may be required in bullet points
- [x] [STVL](https://github.com/SteveMacenski/spatio_temporal_voxel_layer)/[NPVL](https://github.com/SteveMacenski/nonpersistent_voxel_layer) plugins
- [ ] Need thoughts on performance evaluation 
- [ ] Usage tutorial

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in docs.nav2.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Comment by elsayedelsheikh** [comment]
Notes:
[PointCloudTransport SubscriberFilter](https://github.com/ros-perception/point_cloud_transport/blob/9fedca3d931346e3de8cc13aaa9e31deab540e0e/point_cloud_transport/include/point_cloud_transport/subscriber_filter.hpp) 
- doesn't have `resubscribe()` method so on Lifecycle activation, it needs to be re-initialized with arguments.
- inherits from `message_filters::SimpleFilter` not `message_filters::SubscriberBase` which don't share common base class so observation_subscribers can't be added to the same vector.

**Comment by elsayedelsheikh** [comment]
@SteveMacenski Any notes about re-initializing the subscriber in `activate()` method ?
If this implementation looks good, I’ll stick with it for the other plugins too. LMK your thoughts!
Thx

**Comment by elsayedelsheikh** [comment]
@SteveMacenski Hey Steve, Can you have a quick look on my implementation?
The build is fine with `point_cloud_transport` source, waiting for the next release to update the binaries with the new API

File: nav2_costmap_2d/include/nav2_costmap_2d/obstacle_layer.hpp [hunk 1]
```diff
@@ -236,12 +237,14 @@ class ObstacleLayer : public CostmapLayer
   laser_geometry::LaserProjection projector_;
   /// @brief Used for the observation message filters
   #if RCLCPP_VERSION_GTE(29, 6, 0)
-  std::vector<std::shared_ptr<message_filters::SubscriberBase>>
-  observation_subscribers_;
+  std::shared_ptr<message_filters::Subscriber<sensor_msgs::msg::LaserScan>>
```
Comment (SteveMacenski) [inline nav2_costmap_2d/include/nav2_costmap_2d/obstacle_layer.hpp]: I think we still want a vector of these for multiple possible input topics per layers (which is common)

File: nav2_costmap_2d/plugins/obstacle_layer.cpp [hunk 2]
```diff
@@ -278,36 +282,35 @@ void ObstacleLayer::onInitialize()
...
 
-      observation_subscribers_.push_back(sub);
+      observation_subscribers_laser_ = std::move(sub);
 
       observation_notifiers_.push_back(filter);
       observation_notifiers_.back()->setTolerance(rclcpp::Duration::from_seconds(
           tf_filter_tolerance));
 
     } else {
-      // For Kilted and Older Support from Message Filters API change
```
Comment (SteveMacenski) [inline nav2_costmap_2d/plugins/obstacle_layer.cpp:290]: Does transport work with just normal topics when its not a pointcloud transport publisher? I want to make sure by removing this we're not removing support for current behavior that doesn't use the pointcloud transport. This should be additive, not a replacement

File: nav2_costmap_2d/plugins/obstacle_layer.cpp [hunk 3]
```diff
@@ -278,36 +282,35 @@ void ObstacleLayer::onInitialize()
...
-      sub = std::make_shared<message_filters::Subscriber<sensor_msgs::msg::PointCloud2,
-          rclcpp_lifecycle::LifecycleNode>>(node, topic, custom_qos_profile, sub_opt);
-      // For Humble and Older compatibility in Message Filters API change
-      #else
-      sub = std::make_shared<message_filters::Subscriber<sensor_msgs::msg::PointCloud2,
-          rclcpp_lifecycle::LifecycleNode>>(
-          node, topic, custom_qos_profile.get_rmw_qos_profile(), sub_opt);
-      #endif
-
+      std::shared_ptr<rclcpp::node_interfaces::NodeInterfaces<
```
Comment (SteveMacenski) [inline nav2_costmap_2d/plugins/obstacle_layer.cpp]: `auto` here might do you some readability favors :-)

File: nav2_costmap_2d/plugins/obstacle_layer.cpp [hunk 4]
```diff
@@ -278,36 +282,35 @@ void ObstacleLayer::onInitialize()
...
+          rclcpp::node_interfaces::NodeBaseInterface,
+          rclcpp::node_interfaces::NodeParametersInterface,
+          rclcpp::node_interfaces::NodeTopicsInterface,
+          rclcpp::node_interfaces::NodeLoggingInterface
+        >> node_interfaces = std::make_shared<
+        rclcpp::node_interfaces::NodeInterfaces<
```
Comment (SteveMacenski) [inline nav2_costmap_2d/plugins/obstacle_layer.cpp]: I think these templates can be automatically deduced from the constructor arguments, no?

File: nav2_costmap_2d/plugins/obstacle_layer.cpp [hunk 5]
```diff
@@ -278,36 +282,35 @@ void ObstacleLayer::onInitialize()
...
+        >(
+            node->get_node_base_interface(),
+            node->get_node_parameters_interface(),
+            node->get_node_topics_interface(),
+            node->get_node_logging_interface()
+        );
+      std::shared_ptr<point_cloud_transport::SubscriberFilter> sub;
+      sub = std::make_shared<point_cloud_transport::SubscriberFilter>(
+        node_interfaces, topic,
+        point_cloud_transport);
```
Comment (SteveMacenski) [inline nav2_costmap_2d/plugins/obstacle_layer.cpp]: What about QoS and `sub_opt` settings? Does this start as subscribing? If so, we'd need to pass those in so we don't later change those settings in the subscribe below

File: nav2_costmap_2d/plugins/obstacle_layer.cpp [hunk 6]
```diff
@@ -771,21 +774,59 @@ ObstacleLayer::activate()
...
+
+    rmw_qos_profile_t custom_qos = rmw_qos_profile_sensor_data;
+    custom_qos.depth = 50;
+    auto sub_opt = rclcpp::SubscriptionOptions();
+    sub_opt.callback_group = callback_group_;
+
+    // PCT->getTopic() method doesn't work correctly
+    observation_subscribers_pointcloud_->subscribe(
+      node_interfaces,
+      "/rgbd_camera/points",
```
Comment (SteveMacenski) [inline nav2_costmap_2d/plugins/obstacle_layer.cpp]: We should have this parameter stored somewhere to pull from

File: nav2_costmap_2d/plugins/obstacle_layer.cpp [hunk 7]
```diff
@@ -771,21 +774,59 @@ ObstacleLayer::activate()
...
+      >
+      >(
+          node->get_node_base_interface(),
+          node->get_node_parameters_interface(),
+          node->get_node_topics_interface(),
+          node->get_node_logging_interface()
+      );
+
+    rmw_qos_profile_t custom_qos = rmw_qos_profile_sensor_data;
+    custom_qos.depth = 50;
```
Comment (SteveMacenski) [inline nav2_costmap_2d/plugins/obstacle_layer.cpp]: This does not match `sub_opt`

**Comment by SteveMacenski** [comment]
@elsayedelsheikh thanks for taking this on!

It might be nice to change the Transport code to have this constructor be templated by `NodeT` https://github.com/ros-perception/point_cloud_transport/blob/9fedca3d931346e3de8cc13aaa9e31deab540e0e/point_cloud_transport/include/point_cloud_transport/subscriber_filter.hpp#L75-L85 with a default of `rclcpp::Node` when not otherwise specified. That would give the same behavior as before, but let us use this with the lifecycle node.  It would involve a PR over there, but that's a good contribution.

Maybe there are a couple of PRs to PC2 Transport needed to make this possible? Such as :

> doesn't have resubscribe() method so on Lifecycle activation, it needs to be re-initialized with arguments.

> inherits from message_filters::SimpleFilter not message_filters::SubscriberBase which don't share common base class so observation_subscribers can't be added to the same vector.

It strikes me that perhaps they are not included for a technical reason but rather just not feature parallel to what we use now. They could possibly be implemented :-) Especially if these features are in the Image Transport (you should check), in which case they are direct analogs to be added here that should be easy merges for the maintainers. Might be good to look over the issues or file an issue about some of these items

File: nav2_costmap_2d/include/nav2_costmap_2d/obstacle_layer.hpp (hunk 1 above)
Comment (elsayedelsheikh) [reply nav2_costmap_2d/include/nav2_costmap_2d/obstacle_layer.hpp]: is it fine to have two separate vectors, one for LaserScan data and another for PointCloud data?
```bash
  std::vector<std::shared_ptr<message_filters::Subscriber<sensor_msgs::msg::LaserScan>>
  observation_subscribers_laser_;
  std::vector<std::shared_ptr<point_cloud_transport::SubscriberFilter>>
  observation_subscribers_pointcloud_;
```
Even if I got them into a single void vector, the operations are different for these two classes

File: nav2_costmap_2d/plugins/obstacle_layer.cpp (hunk 2 above)
Comment (elsayedelsheikh) [reply nav2_costmap_2d/plugins/obstacle_layer.cpp:290]: Yes, `raw` transport is just a normal `PointCloud2`, I also tested the behavior in the simulation.

File: nav2_costmap_2d/plugins/obstacle_layer.cpp (hunk 3 above)
Comment (elsayedelsheikh) [reply nav2_costmap_2d/plugins/obstacle_layer.cpp]: This also works :)
```bash
    auto node_interfaces = std::make_shared<
      rclcpp::node_interfaces::NodeInterfaces<
        rclcpp::node_interfaces::NodeBaseInterface,
        rclcpp::node_interfaces::NodeParametersInterface,
        rclcpp::node_interfaces::NodeTopicsInterface,
        rclcpp::node_interfaces::NodeLoggingInterface
      >
      >(*node);
```
But I tried to keep things explicit to avoid any compiling problems on other platforms
Ok then, I'll use `auto`

File: nav2_costmap_2d/plugins/obstacle_layer.cpp (hunk 4 above)
Comment (elsayedelsheikh) [reply nav2_costmap_2d/plugins/obstacle_layer.cpp]: Yup

File: nav2_costmap_2d/plugins/obstacle_layer.cpp (hunk 5 above)
Comment (elsayedelsheikh) [reply nav2_costmap_2d/plugins/obstacle_layer.cpp]: Yes, It starts subscribing with `rmw_qos_profile_default` and `rclcpp::SubscriptionOptions()`
We can use the default constructor that and then `subscribe` as below:
```bash
      sub = std::make_shared<point_cloud_transport::SubscriberFilter>();
      sub->subscribe(node_interfaces, topic, point_cloud_transport, custom_qos, sub_opts);
```

**Comment by elsayedelsheikh** [comment]
> @elsayedelsheikh thanks for taking this on!

My Pleasure,  I was waiting for this :-)
> It might be nice to change the Transport code to have this constructor be templated by `NodeT` https://github.com/ros-perception/point_cloud_transport/blob/9fedca3d931346e3de8cc13aaa9e31deab540e0e/point_cloud_transport/include/point_cloud_transport/subscriber_filter.hpp#L75-L85 with a default of `rclcpp::Node` when not otherwise specified. That would give the same behavior as before, but let us use this with the lifecycle node. It would involve a PR over there, but that's a good contribution.

Our first implementation was actually based on [templated constructor](https://github.com/elsayedelsheikh/point_cloud_transport/blob/fd9616736df34ed53e3e20d92c0d96979204b97b/point_cloud_transport/include/point_cloud_transport/point_cloud_transport.hpp#L155C1-L162C1) but we followed this https://github.com/ros-perception/point_cloud_transport/pull/109#pullrequestreview-2702512986 similar to https://github.com/ros2/geometry2/issues/698 which recommends avoiding templates.
 

> 
> Maybe there are a couple of PRs to PC2 Transport needed to make this possible? Such as :
> 
> > doesn't have resubscribe() method so on Lifecycle activation, it needs to be re-initialized with arguments.
> 
> > inherits from message_filters::SimpleFilter not message_filters::SubscriberBase which don't share common base class so observation_subscribers can't be added to the same vector.
> It strikes me that perhaps they are not included for a technical reason but rather just not feature parallel to what we use now. They could possibly be implemented :-) Especially if these features are in the Image Transport (you should check), in which case they are direct analogs to be added here that should be easy merges for the maintainers. Might be good to look over the issues or file an issue about some of these items

OK, Sure!

File: nav2_costmap_2d/plugins/obstacle_layer.cpp (hunk 2 above)
Comment (SteveMacenski) [reply nav2_costmap_2d/plugins/obstacle_layer.cpp:290]: But what about the topic names it subscribes to? The `Raw` I assume is `<my_topic>/raw` and `<my_topic>/compressed` similar to image transport, no? Would all the PC2s need to be configured with `<my_topic>` but actually publish on `<my_topic>/raw`? Perhaps PC2 transport is different than image transport, so please correct me if I'm wrong :-)

File: nav2_costmap_2d/include/nav2_costmap_2d/obstacle_layer.hpp (hunk 1 above)
Comment (SteveMacenski) [reply nav2_costmap_2d/include/nav2_costmap_2d/obstacle_layer.hpp]: I think that could work, but it would be great if you spent a few minutes looking into the API of the message filter + PC2 transport to see if we can make a new base class or modify the existing base classes to make this work similar to how it works now with the `SubscriberBase`. I see both have mainly API subscribe / unsubscribe APIs but they differ in the arguments. Maybe there's a way to change this so that message filters has the update needed to make this work since I think its a useful feature for the community, not just Nav2.

For example: it looks like the issue is mostly just providing the `transport` on subscribe. Maybe we can instead have a `setTransport()` API or use the value given in the constructor so that the `subscribes` could look like the message filter subscriber base class'.  

- https://github.com/ros-perception/point_cloud_transport/blob/9fedca3d931346e3de8cc13aaa9e31deab540e0e/point_cloud_transport/include/point_cloud_transport/subscriber_filter.hpp#L63
- https://github.com/ros2/message_filters/blob/rolling/include/message_filters/subscriber.hpp#L137-L139

File: nav2_costmap_2d/plugins/obstacle_layer.cpp (hunk 4 above)
Comment (SteveMacenski) [reply nav2_costmap_2d/plugins/obstacle_layer.cpp]: Lets not specify lots of templates unless we strictly need to, it makes the code a bit less easily readable

File: nav2_costmap_2d/plugins/obstacle_layer.cpp (hunk 3 above)
Comment (SteveMacenski) [reply nav2_costmap_2d/plugins/obstacle_layer.cpp]: Is the second level of templating actually needed? I also wonder if that is not deduced.

File: nav2_costmap_2d/plugins/obstacle_layer.cpp (hunk 5 above)
Comment (SteveMacenski) [reply nav2_costmap_2d/plugins/obstacle_layer.cpp]: Ok! That's actually better since the default constructor doesn't try to subscribe automatically at start https://github.com/ros-perception/point_cloud_transport/blob/9fedca3d931346e3de8cc13aaa9e31deab540e0e/point_cloud_transport/src/subscriber_filter.cpp#L48-L50

**Comment by SteveMacenski** [comment]
It might be good to consolidate a list of 'wants' and 'proposed changes' and file a ticket with me CCed in it in PC2 Transport for us to discuss with the maintainers. I really hate working with the node interfaces in the application code (i.e. Nav2) since I believe it should be hidden from me as a developer. Templates do that quite nicely. I'm not saying we have to remove the current interface constructors, but it would be nice to have a template option as well that calls the interface once in the library. [They essentially already do that here](https://github.com/ros-perception/point_cloud_transport/blob/9fedca3d931346e3de8cc13aaa9e31deab540e0e/point_cloud_transport/src/subscriber_filter.cpp#L65-L69) but only for `rclcpp::Node`. Just template that function and this would work well for us.

File: nav2_costmap_2d/plugins/obstacle_layer.cpp (hunk 4 above)
Comment (elsayedelsheikh) [reply nav2_costmap_2d/plugins/obstacle_layer.cpp]: Noted!

File: nav2_costmap_2d/plugins/obstacle_layer.cpp (hunk 3 above)
Comment (elsayedelsheikh) [reply nav2_costmap_2d/plugins/obstacle_layer.cpp]: Yeah!
```bash
/usr/include/c++/13/bits/shared_ptr.h:1005:5: note:   template argument deduction/substitution failed:
/workspaces/dev_ws/src/navigation2/nav2_costmap_2d/plugins/obstacle_layer.cpp:294:10: error: type/value mismatch at argument 1 in template parameter list for ‘template<class _Tp, class ... _Args> std::shared_ptr<typename std::enable_if<(! std::is_array< <template-parameter-1-1> >::value), _Tp>::type> std::make_shared(_Args&& ...)’
  292 |       auto node_interfaces = std::make_shared<
      |                              ~~~~~~~~~~~~~~~~~
  293 |         rclcpp::node_interfaces::NodeInterfaces
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  294 |         >(
      |         ~^
  295 |             node->get_node_base_interface(),
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  296 |             node->get_node_parameters_interface(),
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  297 |             node->get_node_topics_interface(),
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  298 |             node->get_node_logging_interface()
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  299 |         );
      |         ~ 
/workspaces/dev_ws/src/navigation2/nav2_costmap_2d/plugins/obstacle_layer.cpp:294:10: note:   expected a type, got ‘NodeInterfaces’
```

File: nav2_costmap_2d/plugins/obstacle_layer.cpp (hunk 2 above)
Comment (elsayedelsheikh) [reply nav2_costmap_2d/plugins/obstacle_layer.cpp:290]: PC2 transports works directly with `<my_topic>` when `raw` transport is used...
One more addition I'm having in mind, There's a `republish` node that can be used to receive any kind of transport and publish another PC2 compressed type or even all available plugins, for example: receive `<my_topic>` of type `raw` and publish `<my_topic>/draco`, `<my_topic>/zstd` and `<my_topic>/zlib` so maybe the user can specify which type of transport to be used internally in `nav2` even if he's providing different in_transport to `nav2`.

**Comment by elsayedelsheikh** [comment]
> It might be good to consolidate a list of 'wants' and 'proposed changes' and file a ticket with me CCed in it in PC2 Transport for us to discuss with the maintainers. I really hate working with the node interfaces in the application code (i.e. Nav2) since I believe it should be hidden from me as a developer. Templates do that quite nicely. I'm not saying we have to remove the current interface constructors, but it would be nice to have a template option as well that calls the interface once in the library. [They essentially already do that here](https://github.com/ros-perception/point_cloud_transport/blob/9fedca3d931346e3de8cc13aaa9e31deab540e0e/point_cloud_transport/src/subscriber_filter.cpp#L65-L69) but only for `rclcpp::Node`. Just template that function and this would work well for us.

Agreed!

File: nav2_costmap_2d/include/nav2_costmap_2d/obstacle_layer.hpp (hunk 1 above)
Comment (elsayedelsheikh) [reply nav2_costmap_2d/include/nav2_costmap_2d/obstacle_layer.hpp]: Working on it :)

**Comment by SteveMacenski** [comment]
This ready for a review again?

**Comment by elsayedelsheikh** [comment]
> This ready for a review again?

Yeah, I tested the new signatures and it works fine! 
I didn't change the PR status till I get the other parts done as well :)

File: nav2_costmap_2d/plugins/obstacle_layer.cpp [hunk 8]
```diff
@@ -158,6 +158,8 @@ void ObstacleLayer::onInitialize()
     declareParameter(source + "." + "obstacle_min_range", rclcpp::ParameterValue(0.0));
     declareParameter(source + "." + "raytrace_max_range", rclcpp::ParameterValue(3.0));
     declareParameter(source + "." + "raytrace_min_range", rclcpp::ParameterValue(0.0));
+    declareParameter(source + "." + "point_cloud_transport",
```
Comment (SteveMacenski) [inline nav2_costmap_2d/plugins/obstacle_layer.cpp]: Add to configuration files the population of this parameter with a commented out bit on the available options for consideration

File: nav2_costmap_2d/plugins/obstacle_layer.cpp [hunk 9]
```diff
@@ -173,6 +175,8 @@ void ObstacleLayer::onInitialize()
     node->get_parameter(name_ + "." + source + "." + "inf_is_valid", inf_is_valid);
     node->get_parameter(name_ + "." + source + "." + "marking", marking);
     node->get_parameter(name_ + "." + source + "." + "clearing", clearing);
+    node->get_parameter(name_ + "." + source + "." + "point_cloud_transport",
```
Comment (SteveMacenski) [inline nav2_costmap_2d/plugins/obstacle_layer.cpp]: New param should be in the configuration guide :-)

File: nav2_costmap_2d/plugins/obstacle_layer.cpp [hunk 10]
```diff
@@ -287,32 +291,8 @@ void ObstacleLayer::onInitialize()
...
-        topic, custom_qos_profile, sub_opt);
-      // For Humble and Older compatibility in Message Filters API change
-      #else
-      sub = std::make_shared<message_filters::Subscriber<sensor_msgs::msg::PointCloud2,
-          rclcpp_lifecycle::LifecycleNode>>(
-        std::static_pointer_cast<rclcpp_lifecycle::LifecycleNode>(node),
-        topic, custom_qos_profile.get_rmw_qos_profile(), sub_opt);
-      #endif
-
+      auto sub = std::make_shared<point_cloud_transport::SubscriberFilter>(
```
Comment (SteveMacenski) [inline nav2_costmap_2d/plugins/obstacle_layer.cpp]: I think you need to readd the backward compatibility for Jazzy/Kilted

**Review by SteveMacenski — CHANGES_REQUESTED** [review]
Generally approved! Are we just waiting on the PC transport code to be released into binaries?

File: nav2_costmap_2d/plugins/obstacle_layer.cpp (hunk 8 above)
Comment (elsayedelsheikh) [reply nav2_costmap_2d/plugins/obstacle_layer.cpp]: Renamed the parameter
```yaml
        observation_sources: pointcloud
        pointcloud:
          transport_type: "raw" # Options: raw, zlib, draco, zstd
```
Which files exactly do I need to update? 
- `nav2_bringup`.`nav2_params` Default to `LaserScan` so nothing to update
- Update `docs.nav2.org` right? 
- anything else?

File: nav2_costmap_2d/plugins/obstacle_layer.cpp (hunk 10 above)
Comment (elsayedelsheikh) [reply nav2_costmap_2d/plugins/obstacle_layer.cpp]: Any links/guides to follow ?

**Comment by elsayedelsheikh** [comment]
> Generally approved! Are we just waiting on the PC transport code to be released into binaries?

I've just updated `nav2_collision_monitor`.
We're ready to merge whenever PCT is released

File: nav2_costmap_2d/plugins/obstacle_layer.cpp (hunk 8 above)
Comment (SteveMacenski) [reply nav2_costmap_2d/plugins/obstacle_layer.cpp]: That's it I suppose, yes!

File: nav2_costmap_2d/plugins/obstacle_layer.cpp (hunk 10 above)
Comment (SteveMacenski) [reply nav2_costmap_2d/plugins/obstacle_layer.cpp]: Undelete the code deleted and just update the block for `main/rolling` :wink:

**Comment by SteveMacenski** [comment]
@elsayedelsheikh check out uncrustify failures to fix please! Also the documentation update PR would be dandy

File: nav2_collision_monitor/src/pointcloud.cpp [hunk 11]
```diff
@@ -131,6 +136,8 @@ void PointCloud::getParameters(std::string & source_topic)
   nav2::declare_parameter_if_not_declared(
     node, source_name_ + ".min_range", rclcpp::ParameterValue(0.0));
   min_range_ = node->get_parameter(source_name_ + ".min_range").as_double();
+    node, source_name_ + ".transport_type", rclcpp::ParameterValue(std::string("raw")));
+  transport_type_ = node->get_parameter(source_name_ + ".transport_type").as_string();
```
Comment (SteveMacenski) [inline nav2_collision_monitor/src/pointcloud.cpp:150]: This... doesn't look right

File: nav2_collision_monitor/src/pointcloud.cpp [hunk 12]
```diff
@@ -60,10 +60,15 @@ void PointCloud::configure()
 
   getParameters(source_topic);
 
-  data_sub_ = node->create_subscription<sensor_msgs::msg::PointCloud2>(
-    source_topic,
+  const point_cloud_transport::TransportHints hint(transport_type_);
+
```
Comment (SteveMacenski) [inline nav2_collision_monitor/src/pointcloud.cpp]:
```suggestion
```

File: nav2_collision_monitor/src/pointcloud.cpp [hunk 13]
```diff
@@ -60,10 +60,15 @@ void PointCloud::configure()
...
+  pct_ = std::make_shared<point_cloud_transport::PointCloudTransport>(*node);
+
```
Comment (SteveMacenski) [inline nav2_collision_monitor/src/pointcloud.cpp]:
```suggestion
```

**Review by SteveMacenski — CHANGES_REQUESTED** [review]

File: nav2_costmap_2d/plugins/obstacle_layer.cpp (hunk 8 above)
Comment (SteveMacenski) [reply nav2_costmap_2d/plugins/obstacle_layer.cpp]: Also for the collision monitor as well!

**Comment by elsayedelsheikh** [comment]
> @elsayedelsheikh check out uncrustify failures to fix please! Also the documentation update PR would be dandy

- Done here ✅ 
- Moving to docs PR!

File: nav2_collision_monitor/include/nav2_collision_monitor/pointcloud.hpp [hunk 14]
```diff
@@ -98,7 +99,9 @@ class PointCloud : public Source
   // ----- Variables -----
 
   /// @brief PointCloud data subscriber
-  nav2::Subscription<sensor_msgs::msg::PointCloud2>::SharedPtr data_sub_;
+  std::shared_ptr<point_cloud_transport::PointCloudTransport> pct_;
```
Comment (SteveMacenski) [inline nav2_collision_monitor/include/nav2_collision_monitor/pointcloud.hpp:103]: I think we need the preprocessor ifs here for rolling and newer and kilted and older so this compiles with jazzy and kilted

File: nav2_collision_monitor/src/pointcloud.cpp [hunk 15]
```diff
@@ -60,10 +60,13 @@ void PointCloud::configure()
 
   getParameters(source_topic);
 
-  data_sub_ = node->create_subscription<sensor_msgs::msg::PointCloud2>(
```
Comment (SteveMacenski) [inline nav2_collision_monitor/src/pointcloud.cpp:63]: Ditto

**Review by SteveMacenski — COMMENTED** [review]
The Jazzy/Kilted jobs should be passing, so I think we need to make updates for the compilation errors we see in those jobs. Only the main build should be failing from this PR since only the main branch should have the PC2 transport enabled

**Comment by elsayedelsheikh** [comment]
@SteveMacenski Jazzy/Kilted jobs Passed :white_check_mark:

**Comment by SteveMacenski** [comment]
@elsayedelsheikh the main PR doesn't build :-) 

```
--- stderr: nav2_costmap_2d                   
/opt/overlay_ws/src/navigation2/nav2_costmap_2d/plugins/obstacle_layer.cpp: In member function ‘virtual void nav2_costmap_2d::ObstacleLayer::onInitialize()’:
/opt/overlay_ws/src/navigation2/nav2_costmap_2d/plugins/obstacle_layer.cpp:344:41: error: no matching function for call to ‘std::vector<std::shared_ptr<message_filters::SubscriberBase> >::push_back(std::shared_ptr<point_cloud_transport::SubscriberFilter>&)’
  344 |       observation_subscribers_.push_back(sub);
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
```

Once that is squared away, we just need those documentation updates for docs.nav2.org on the configuration guide + the migration guide about the new feature

File: nav2_collision_monitor/src/pointcloud.cpp [hunk 16]
```diff
@@ -45,7 +45,11 @@ PointCloud::PointCloud(
 PointCloud::~PointCloud()
 {
   RCLCPP_INFO(logger_, "[%s]: Destroying PointCloud", source_name_.c_str());
+  #if RCLCPP_VERSION_GTE(30, 0, 0)
+  data_sub_.shutdown();
```
Comment (SteveMacenski) [inline nav2_collision_monitor/src/pointcloud.cpp:49]: Reset pct_ as well?

**Review by SteveMacenski — CHANGES_REQUESTED** [review]
I also see CI failing very oddly. I just retriggered it but if we fail in a similar way again, we may need to look into it.

For now, a small bug fix to close out the transport as well as the subscriber

File: nav2_collision_monitor/src/pointcloud.cpp (hunk 16 above)
Comment (elsayedelsheikh) [reply nav2_collision_monitor/src/pointcloud.cpp:49]: pct_ can be safely used again to re-subscribe, only subscription or/ publishers shutdown are required.

Comment (SteveMacenski) [reply nav2_collision_monitor/src/pointcloud.cpp:49]: This is the destructor - they wouldn't be used again :-)

**Comment by elsayedelsheikh** [comment]
> I also see CI failing very oddly. I just retriggered it but if we fail in a similar way again, we may need to look into it.

After rebasing to recent updates,  Jazzy & Kilted builds are failing due to missing header files `tf2_ros/buffer.hpp`
```bash
#10 197.6 --- stderr: nav2_util
#10 197.6 In file included from /root/ws/src/nav2_util/src/robot_utils.cpp:25:
#10 197.6 /root/ws/src/nav2_util/include/nav2_util/robot_utils.hpp:29:10: fatal error: tf2_ros/buffer.hpp: No such file or directory
#10 197.6    29 | #include "tf2_ros/buffer.hpp"
#10 197.6       |          ^~~~~~~~~~~~~~~~~~~~
#10 197.6 compilation terminated.
#10 197.6 gmake[2]: *** [src/CMakeFiles/nav2_util_core.dir/build.make:118: src/CMakeFiles/nav2_util_core.dir/robot_utils.cpp.o] Error 1
#10 197.6 gmake[2]: *** Waiting for unfinished jobs....
#10 197.6 gmake[1]: *** [CMakeFiles/Makefile2:210: src/CMakeFiles/nav2_util_core.dir/all] Error 2
#10 197.6 gmake[1]: *** Waiting for unfinished jobs....
#10 197.6 gmake: *** [Makefile:146: all] Error 2
#10 197.6 ---
#10 197.6 Failed   <<< nav2_util [12.2s, exited with code 2]
```

File: nav2_collision_monitor/src/pointcloud.cpp (hunk 16 above)
Comment (elsayedelsheikh) [reply nav2_collision_monitor/src/pointcloud.cpp:49]: Oh 😅 then it goes out of scope and it's a shared pointer, we don't need to do anything about it
Anyway, it doesn't have a reset function 😀

**Comment by SteveMacenski** [comment]
Yeah that's fine - I'm looking at the circleCI job for `rolling` which had a weird failure. The kilted/jazzy are known due to those API changes (will come back in the coming weeks once Jazzy/Kilted have new binary releases to reflect those API chaneges as well)

**Comment by elsayedelsheikh** [comment]
> Yeah that's fine - I'm looking at the circleCI job for `rolling` which had a weird failure. The kilted/jazzy are known due to those API changes (will come back in the coming weeks once Jazzy/Kilted have new binary releases to reflect those API chaneges as well)

Perfect!

**Comment by SteveMacenski** [comment]
@elsayedelsheikh can you show this building on jazzy/kilted prior to rebase? Our CI is down for those at the moment as I mentioned above and I want to verify those work before I merge since this has changes specific to dfiferent distributions.

**Comment by elsayedelsheikh** [comment]
> @SteveMacenski Jazzy/Kilted jobs Passed ✅

@SteveMacenski They passed since https://github.com/ros-navigation/navigation2/commit/e2f7fd19d9827b474434c78d9893d573e50cc177 

image
